---
name: CodeceptJS
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-codeceptjs:
    name: "CodeceptJS run with Playwright and ResembleHelper"
    runs-on: mcr.microsoft.com/playwright:focal
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run NPM install"
        run: "npm ci"
      - name: "Run CodeceptJS"
        run: "npm run test"
      - name: Archive report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: |
            tests/output
    strategy:
      fail-fast: false
